version: "3.9"

services:

  web:
    build: web
    volumes:
      - ./web/content:/usr/share/nginx/html
    ports:
      - "80"
    restart: always
#    networks:
#    - "webapp" 

  proxy:
    build: proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    volumes:
      - ./proxy/content:/etc/nginx/conf.d/
      - ./proxy/ssl:/etc/nginx/ssl
      - /var/run/docker.sock:/docker.sock
    restart: always
#    networks:
#    - "webapp"     
#networks:
#  webapp:
#    external: true
    
